import Grapes from "../assets/items/Grapes.png";
import Apples from "../assets/items/Apples.png";
import DanjouPear from "../assets/items/DanjouPear.png";
import Mango from "../assets/items/Mango.png";
import SeedlessWatermelon from "../assets/items/SeedlessWatermelon.png";
import Strawberries from "../assets/items/Strawberries.png";
import frozen from "../assets/categories/Frozen.png";
import BabyCare from "../assets/categories/babycare.jpg";
import Bakery from "../assets/categories/Bakery.png";
import Beverages from "../assets/categories/Beverages.png";
import DryFoodNuts from "../assets/categories/DryFood&Nuts.png";
import FishSeafood from "../assets/categories/Fish&Seafood.png";
import FreshMeat from "../assets/categories/FreshMeat.png";
import FruitsVegetables from "../assets/categories/Fruits&Vegetables.png";
import HomeCare from "../assets/categories/HomeCare.png";
import InstantFood from "../assets/categories/InstantFood.png";
import PersonalCare from "../assets/categories/PersonalCare.png";
import PetCare from "../assets/categories/PetCare.png";

const getRandom = (max) => {
  return Math.floor(Math.random() * max);
};

export const AllItems = [
  {
    id: "01",
    category: "Frozen",
    image: frozen,
    subCategories: [
      {
        name: "Doughs",
        items: [
          {
            name: "Black Seedless Grapes",
            price: 80,
            image: Grapes,
            description: "",
            category: "",
            id: 1,
            amount: 0,
          },
          {
            name: "Champagne Mango Pack",
            price: 80,
            image: Mango,
            description: "",
            category: "",
            id: 2,
            amount: 0,
          },
          {
            name: "Organic Pink Lady Apples",
            price: 80,
            image: Apples,
            description: "",
            category: "",
            id: 3,
            amount: 0,
          },
          {
            name: "Driscoll's Strawberries",
            price: 80,
            image: Strawberries,
            description: "",
            category: "",
            id: 4,
            amount: 0,
          },
          {
            name: "Seedless Watermelon",
            price: 80,
            image: SeedlessWatermelon,
            description: "",
            category: "",
            id: 5,
            amount: 0,
          },
          {
            name: "Danjou Pear",
            price: 80,
            image: DanjouPear,
            description: "",
            category: "",
            id: 6,
            amount: 0,
          },
        ],
      },
      {
        name: "Frozen fruits and vegetables",
        items: [
          {
            name: "Black Seedless Grapes",
            price: 80,
            image: Grapes,
            description: "",
            category: "",
            id: 1,
            amount: 0,
          },
          {
            name: "Champagne Mango Pack",
            price: 80,
            image: Mango,
            description: "",
            category: "",
            id: 2,
            amount: 0,
          },
          {
            name: "Organic Pink Lady Apples",
            price: 80,
            image: Apples,
            description: "",
            category: "",
            id: 3,
            amount: 0,
          },
          {
            name: "Driscoll's Strawberries",
            price: 80,
            image: Strawberries,
            description: "",
            category: "",
            id: 4,
            amount: 0,
          },
          {
            name: "Seedless Watermelon",
            price: 80,
            image: SeedlessWatermelon,
            description: "",
            category: "",
            id: 5,
            amount: 0,
          },
          {
            name: "Danjou Pear",
            price: 80,
            image: DanjouPear,
            description: "",
            category: "",
            id: 6,
            amount: 0,
          },
        ],
      },
      {
        name: "Ice cream and popsicles",
        items: [
          {
            name: "Black Seedless Grapes",
            price: 80,
            image: Grapes,
            description: "",
            category: "",
            id: 1,
            amount: 0,
          },
          {
            name: "Champagne Mango Pack",
            price: 80,
            image: Mango,
            description: "",
            category: "",
            id: 2,
            amount: 0,
          },
          {
            name: "Organic Pink Lady Apples",
            price: 80,
            image: Apples,
            description: "",
            category: "",
            id: 3,
            amount: 0,
          },
          {
            name: "Driscoll's Strawberries",
            price: 80,
            image: Strawberries,
            description: "",
            category: "",
            id: 4,
            amount: 0,
          },
          {
            name: "Seedless Watermelon",
            price: 80,
            image: SeedlessWatermelon,
            description: "",
            category: "",
            id: 5,
            amount: 0,
          },
          {
            name: "Danjou Pear",
            price: 80,
            image: DanjouPear,
            description: "",
            category: "",
            id: 6,
            amount: 0,
          },
        ],
      },
      {
        name: "Prepared Food",
        items: [
          {
            name: "Black Seedless Grapes",
            price: 80,
            image: Grapes,
            description: "",
            category: "",
            id: 1,
            amount: 0,
          },
          {
            name: "Champagne Mango Pack",
            price: 80,
            image: Mango,
            description: "",
            category: "",
            id: 2,
            amount: 0,
          },
          {
            name: "Organic Pink Lady Apples",
            price: 80,
            image: Apples,
            description: "",
            category: "",
            id: 3,
            amount: 0,
          },
          {
            name: "Driscoll's Strawberries",
            price: 80,
            image: Strawberries,
            description: "",
            category: "",
            id: 4,
            amount: 0,
          },
          {
            name: "Seedless Watermelon",
            price: 80,
            image: SeedlessWatermelon,
            description: "",
            category: "",
            id: 5,
            amount: 0,
          },
          {
            name: "Danjou Pear",
            price: 80,
            image: DanjouPear,
            description: "",
            category: "",
            id: 6,
            amount: 0,
          },
        ],
      },
    ],
  },
  {
    category: "Baby Care",
    id: "02",
    image: BabyCare,
    subCategories: [
      {
        name: "Baby Accessories",
        items: [
          {
            name: "Black Seedless Grapes",
            price: 80,
            image: Grapes,
            description: "",
            category: "",
            id: 1,
            amount: 0,
          },
          {
            name: "Champagne Mango Pack",
            price: 80,
            image: Mango,
            description: "",
            category: "",
            id: 2,
            amount: 0,
          },
          {
            name: "Organic Pink Lady Apples",
            price: 80,
            image: Apples,
            description: "",
            category: "",
            id: 3,
            amount: 0,
          },
          {
            name: "Driscoll's Strawberries",
            price: 80,
            image: Strawberries,
            description: "",
            category: "",
            id: 4,
            amount: 0,
          },
          {
            name: "Seedless Watermelon",
            price: 80,
            image: SeedlessWatermelon,
            description: "",
            category: "",
            id: 5,
            amount: 0,
          },
          {
            name: "Danjou Pear",
            price: 80,
            image: DanjouPear,
            description: "",
            category: "",
            id: 6,
            amount: 0,
          },
        ],
      },
      {
        name: "Baby Food",
        items: [
          {
            name: "Black Seedless Grapes",
            price: 80,
            image: Grapes,
            description: "",
            category: "",
            id: 1,
            amount: 0,
          },
          {
            name: "Champagne Mango Pack",
            price: 80,
            image: Mango,
            description: "",
            category: "",
            id: 2,
            amount: 0,
          },
          {
            name: "Organic Pink Lady Apples",
            price: 80,
            image: Apples,
            description: "",
            category: "",
            id: 3,
            amount: 0,
          },
          {
            name: "Driscoll's Strawberries",
            price: 80,
            image: Strawberries,
            description: "",
            category: "",
            id: 4,
            amount: 0,
          },
          {
            name: "Seedless Watermelon",
            price: 80,
            image: SeedlessWatermelon,
            description: "",
            category: "",
            id: 5,
            amount: 0,
          },
          {
            name: "Danjou Pear",
            price: 80,
            image: DanjouPear,
            description: "",
            category: "",
            id: 6,
            amount: 0,
          },
        ],
      },
      {
        name: "Baby Hygiene",
        items: [
          {
            name: "Black Seedless Grapes",
            price: 80,
            image: Grapes,
            description: "",
            category: "",
            id: 1,
            amount: 0,
          },
          {
            name: "Champagne Mango Pack",
            price: 80,
            image: Mango,
            description: "",
            category: "",
            id: 2,
            amount: 0,
          },
          {
            name: "Organic Pink Lady Apples",
            price: 80,
            image: Apples,
            description: "",
            category: "",
            id: 3,
            amount: 0,
          },
          {
            name: "Driscoll's Strawberries",
            price: 80,
            image: Strawberries,
            description: "",
            category: "",
            id: 4,
            amount: 0,
          },
          {
            name: "Seedless Watermelon",
            price: 80,
            image: SeedlessWatermelon,
            description: "",
            category: "",
            id: 5,
            amount: 0,
          },
          {
            name: "Danjou Pear",
            price: 80,
            image: DanjouPear,
            description: "",
            category: "",
            id: 6,
            amount: 0,
          },
        ],
      },
    ],
  },
  {
    category: "Bakery",
    id: "03",
    image: Bakery,
    subCategories: [
      {
        name: "Bread",
        items: [
          {
            name: "Black Seedless Grapes",
            price: 80,
            image: Grapes,
            description: "",
            category: "",
            id: 1,
            amount: 0,
          },
          {
            name: "Champagne Mango Pack",
            price: 80,
            image: Mango,
            description: "",
            category: "",
            id: 2,
            amount: 0,
          },
          {
            name: "Organic Pink Lady Apples",
            price: 80,
            image: Apples,
            description: "",
            category: "",
            id: 3,
            amount: 0,
          },
          {
            name: "Driscoll's Strawberries",
            price: 80,
            image: Strawberries,
            description: "",
            category: "",
            id: 4,
            amount: 0,
          },
          {
            name: "Seedless Watermelon",
            price: 80,
            image: SeedlessWatermelon,
            description: "",
            category: "",
            id: 5,
            amount: 0,
          },
          {
            name: "Danjou Pear",
            price: 80,
            image: DanjouPear,
            description: "",
            category: "",
            id: 6,
            amount: 0,
          },
        ],
      },
      {
        name: "Pastry",
        items: [
          {
            name: "Black Seedless Grapes",
            price: 80,
            image: Grapes,
            description: "",
            category: "",
            id: 1,
            amount: 0,
          },
          {
            name: "Champagne Mango Pack",
            price: 80,
            image: Mango,
            description: "",
            category: "",
            id: 2,
            amount: 0,
          },
          {
            name: "Organic Pink Lady Apples",
            price: 80,
            image: Apples,
            description: "",
            category: "",
            id: 3,
            amount: 0,
          },
          {
            name: "Driscoll's Strawberries",
            price: 80,
            image: Strawberries,
            description: "",
            category: "",
            id: 4,
            amount: 0,
          },
          {
            name: "Seedless Watermelon",
            price: 80,
            image: SeedlessWatermelon,
            description: "",
            category: "",
            id: 5,
            amount: 0,
          },
          {
            name: "Danjou Pear",
            price: 80,
            image: DanjouPear,
            description: "",
            category: "",
            id: 6,
            amount: 0,
          },
        ],
      },
    ],
  },
  {
    category: "Beverages",
    id: "04",
    image: Beverages,
    subCategories: [
      {
        name: "Hot Drink",
        items: [
          {
            name: "Black Seedless Grapes",
            price: 80,
            image: Grapes,
            description: "",
            category: "",
            id: 1,
            amount: 0,
          },
          {
            name: "Champagne Mango Pack",
            price: 80,
            image: Mango,
            description: "",
            category: "",
            id: 2,
            amount: 0,
          },
          {
            name: "Organic Pink Lady Apples",
            price: 80,
            image: Apples,
            description: "",
            category: "",
            id: 3,
            amount: 0,
          },
          {
            name: "Driscoll's Strawberries",
            price: 80,
            image: Strawberries,
            description: "",
            category: "",
            id: 4,
            amount: 0,
          },
          {
            name: "Seedless Watermelon",
            price: 80,
            image: SeedlessWatermelon,
            description: "",
            category: "",
            id: 5,
            amount: 0,
          },
          {
            name: "Danjou Pear",
            price: 80,
            image: DanjouPear,
            description: "",
            category: "",
            id: 6,
            amount: 0,
          },
        ],
      },
      {
        name: "Soft Drink",
        items: [
          {
            name: "Black Seedless Grapes",
            price: 80,
            image: Grapes,
            description: "",
            category: "",
            id: 1,
            amount: 0,
          },
          {
            name: "Champagne Mango Pack",
            price: 80,
            image: Mango,
            description: "",
            category: "",
            id: 2,
            amount: 0,
          },
          {
            name: "Organic Pink Lady Apples",
            price: 80,
            image: Apples,
            description: "",
            category: "",
            id: 3,
            amount: 0,
          },
          {
            name: "Driscoll's Strawberries",
            price: 80,
            image: Strawberries,
            description: "",
            category: "",
            id: 4,
            amount: 0,
          },
          {
            name: "Seedless Watermelon",
            price: 80,
            image: SeedlessWatermelon,
            description: "",
            category: "",
            id: 5,
            amount: 0,
          },
          {
            name: "Danjou Pear",
            price: 80,
            image: DanjouPear,
            description: "",
            category: "",
            id: 6,
            amount: 0,
          },
        ],
      },
    ],
  },
  {
    category: "Dry Fruits and Nuts",
    id: "05",
    image: DryFoodNuts,
    subCategories: [
      {
        name: "Fresh dried fruit",
        items: [
          {
            name: "Black Seedless Grapes",
            price: 80,
            image: Grapes,
            description: "",
            category: "",
            id: 1,
            amount: 0,
          },
          {
            name: "Champagne Mango Pack",
            price: 80,
            image: Mango,
            description: "",
            category: "",
            id: 2,
            amount: 0,
          },
          {
            name: "Organic Pink Lady Apples",
            price: 80,
            image: Apples,
            description: "",
            category: "",
            id: 3,
            amount: 0,
          },
          {
            name: "Driscoll's Strawberries",
            price: 80,
            image: Strawberries,
            description: "",
            category: "",
            id: 4,
            amount: 0,
          },
          {
            name: "Seedless Watermelon",
            price: 80,
            image: SeedlessWatermelon,
            description: "",
            category: "",
            id: 5,
            amount: 0,
          },
          {
            name: "Danjou Pear",
            price: 80,
            image: DanjouPear,
            description: "",
            category: "",
            id: 6,
            amount: 0,
          },
        ],
      },
      {
        name: "Nuts and Seeds",
        items: [
          {
            name: "Black Seedless Grapes",
            price: 80,
            image: Grapes,
            description: "",
            category: "",
            id: 1,
            amount: 0,
          },
          {
            name: "Champagne Mango Pack",
            price: 80,
            image: Mango,
            description: "",
            category: "",
            id: 2,
            amount: 0,
          },
          {
            name: "Organic Pink Lady Apples",
            price: 80,
            image: Apples,
            description: "",
            category: "",
            id: 3,
            amount: 0,
          },
          {
            name: "Driscoll's Strawberries",
            price: 80,
            image: Strawberries,
            description: "",
            category: "",
            id: 4,
            amount: 0,
          },
          {
            name: "Seedless Watermelon",
            price: 80,
            image: SeedlessWatermelon,
            description: "",
            category: "",
            id: 5,
            amount: 0,
          },
          {
            name: "Danjou Pear",
            price: 80,
            image: DanjouPear,
            description: "",
            category: "",
            id: 6,
            amount: 0,
          },
        ],
      },
      {
        name: "Packed Dried Fruits",
        items: [
          {
            name: "Black Seedless Grapes",
            price: 80,
            image: Grapes,
            description: "",
            category: "",
            id: 1,
            amount: 0,
          },
          {
            name: "Champagne Mango Pack",
            price: 80,
            image: Mango,
            description: "",
            category: "",
            id: 2,
            amount: 0,
          },
          {
            name: "Organic Pink Lady Apples",
            price: 80,
            image: Apples,
            description: "",
            category: "",
            id: 3,
            amount: 0,
          },
          {
            name: "Driscoll's Strawberries",
            price: 80,
            image: Strawberries,
            description: "",
            category: "",
            id: 4,
            amount: 0,
          },
          {
            name: "Seedless Watermelon",
            price: 80,
            image: SeedlessWatermelon,
            description: "",
            category: "",
            id: 5,
            amount: 0,
          },
          {
            name: "Danjou Pear",
            price: 80,
            image: DanjouPear,
            description: "",
            category: "",
            id: 6,
            amount: 0,
          },
        ],
      },
    ],
  },
  {
    category: "Fish and Seafood",
    id: "06",
    image: FishSeafood,
    subCategories: [
      {
        name: "Fresh fish",
        items: [
          {
            name: "Black Seedless Grapes",
            price: 80,
            image: Grapes,
            description: "",
            category: "",
            id: 1,
            amount: 0,
          },
          {
            name: "Champagne Mango Pack",
            price: 80,
            image: Mango,
            description: "",
            category: "",
            id: 2,
            amount: 0,
          },
          {
            name: "Organic Pink Lady Apples",
            price: 80,
            image: Apples,
            description: "",
            category: "",
            id: 3,
            amount: 0,
          },
          {
            name: "Driscoll's Strawberries",
            price: 80,
            image: Strawberries,
            description: "",
            category: "",
            id: 4,
            amount: 0,
          },
          {
            name: "Seedless Watermelon",
            price: 80,
            image: SeedlessWatermelon,
            description: "",
            category: "",
            id: 5,
            amount: 0,
          },
          {
            name: "Danjou Pear",
            price: 80,
            image: DanjouPear,
            description: "",
            category: "",
            id: 6,
            amount: 0,
          },
        ],
      },
      {
        name: "Frozen fish",
        items: [
          {
            name: "Black Seedless Grapes",
            price: 80,
            image: Grapes,
            description: "",
            category: "",
            id: 1,
            amount: 0,
          },
          {
            name: "Champagne Mango Pack",
            price: 80,
            image: Mango,
            description: "",
            category: "",
            id: 2,
            amount: 0,
          },
          {
            name: "Organic Pink Lady Apples",
            price: 80,
            image: Apples,
            description: "",
            category: "",
            id: 3,
            amount: 0,
          },
          {
            name: "Driscoll's Strawberries",
            price: 80,
            image: Strawberries,
            description: "",
            category: "",
            id: 4,
            amount: 0,
          },
          {
            name: "Seedless Watermelon",
            price: 80,
            image: SeedlessWatermelon,
            description: "",
            category: "",
            id: 5,
            amount: 0,
          },
          {
            name: "Danjou Pear",
            price: 80,
            image: DanjouPear,
            description: "",
            category: "",
            id: 6,
            amount: 0,
          },
        ],
      },
    ],
  },
  {
    category: "Fresh Meat",
    id: "07",
    image: FreshMeat,
    subCategories: [
      {
        name: "Fresh Beef",
        items: [
          {
            name: "Black Seedless Grapes",
            price: 80,
            image: Grapes,
            description: "",
            category: "",
            id: 1,
            amount: 0,
          },
          {
            name: "Champagne Mango Pack",
            price: 80,
            image: Mango,
            description: "",
            category: "",
            id: 2,
            amount: 0,
          },
          {
            name: "Organic Pink Lady Apples",
            price: 80,
            image: Apples,
            description: "",
            category: "",
            id: 3,
            amount: 0,
          },
          {
            name: "Driscoll's Strawberries",
            price: 80,
            image: Strawberries,
            description: "",
            category: "",
            id: 4,
            amount: 0,
          },
          {
            name: "Seedless Watermelon",
            price: 80,
            image: SeedlessWatermelon,
            description: "",
            category: "",
            id: 5,
            amount: 0,
          },
          {
            name: "Danjou Pear",
            price: 80,
            image: DanjouPear,
            description: "",
            category: "",
            id: 6,
            amount: 0,
          },
        ],
      },
      {
        name: "Lamb and Lamb Pieces",
        items: [
          {
            name: "Black Seedless Grapes",
            price: 80,
            image: Grapes,
            description: "",
            category: "",
            id: 1,
            amount: 0,
          },
          {
            name: "Champagne Mango Pack",
            price: 80,
            image: Mango,
            description: "",
            category: "",
            id: 2,
            amount: 0,
          },
          {
            name: "Organic Pink Lady Apples",
            price: 80,
            image: Apples,
            description: "",
            category: "",
            id: 3,
            amount: 0,
          },
          {
            name: "Driscoll's Strawberries",
            price: 80,
            image: Strawberries,
            description: "",
            category: "",
            id: 4,
            amount: 0,
          },
          {
            name: "Seedless Watermelon",
            price: 80,
            image: SeedlessWatermelon,
            description: "",
            category: "",
            id: 5,
            amount: 0,
          },
          {
            name: "Danjou Pear",
            price: 80,
            image: DanjouPear,
            description: "",
            category: "",
            id: 6,
            amount: 0,
          },
        ],
      },
    ],
  },
  {
    category: "Fruits and Vegetables",
    id: "08",
    image: FruitsVegetables,
    subCategories: [
      {
        name: "Vegetables",
        items: [
          {
            name: "Black Seedless Grapes",
            price: 80,
            image: Grapes,
            description: "",
            category: "",
            id: 1,
            amount: 0,
          },
          {
            name: "Champagne Mango Pack",
            price: 80,
            image: Mango,
            description: "",
            category: "",
            id: 2,
            amount: 0,
          },
          {
            name: "Organic Pink Lady Apples",
            price: 80,
            image: Apples,
            description: "",
            category: "",
            id: 3,
            amount: 0,
          },
          {
            name: "Driscoll's Strawberries",
            price: 80,
            image: Strawberries,
            description: "",
            category: "",
            id: 4,
            amount: 0,
          },
          {
            name: "Seedless Watermelon",
            price: 80,
            image: SeedlessWatermelon,
            description: "",
            category: "",
            id: 5,
            amount: 0,
          },
          {
            name: "Danjou Pear",
            price: 80,
            image: DanjouPear,
            description: "",
            category: "",
            id: 6,
            amount: 0,
          },
        ],
      },
      {
        name: "Fruits",
        items: [
          {
            name: "Black Seedless Grapes",
            price: 80,
            image: Grapes,
            description: "",
            category: "",
            id: 1,
            amount: 0,
          },
          {
            name: "Champagne Mango Pack",
            price: 80,
            image: Mango,
            description: "",
            category: "",
            id: 2,
            amount: 0,
          },
          {
            name: "Organic Pink Lady Apples",
            price: 80,
            image: Apples,
            description: "",
            category: "",
            id: 3,
            amount: 0,
          },
          {
            name: "Driscoll's Strawberries",
            price: 80,
            image: Strawberries,
            description: "",
            category: "",
            id: 4,
            amount: 0,
          },
          {
            name: "Seedless Watermelon",
            price: 80,
            image: SeedlessWatermelon,
            description: "",
            category: "",
            id: 5,
            amount: 0,
          },
          {
            name: "Danjou Pear",
            price: 80,
            image: DanjouPear,
            description: "",
            category: "",
            id: 6,
            amount: 0,
          },
        ],
      },
    ],
  },
  {
    category: "Home Care",
    id: "09",
    image: HomeCare,
    subCategories: [
      {
        name: "Household Cleaning",
        items: [
          {
            name: "Black Seedless Grapes",
            price: 80,
            image: Grapes,
            description: "",
            category: "",
            id: 1,
            amount: 0,
          },
          {
            name: "Champagne Mango Pack",
            price: 80,
            image: Mango,
            description: "",
            category: "",
            id: 2,
            amount: 0,
          },
          {
            name: "Organic Pink Lady Apples",
            price: 80,
            image: Apples,
            description: "",
            category: "",
            id: 3,
            amount: 0,
          },
          {
            name: "Driscoll's Strawberries",
            price: 80,
            image: Strawberries,
            description: "",
            category: "",
            id: 4,
            amount: 0,
          },
          {
            name: "Seedless Watermelon",
            price: 80,
            image: SeedlessWatermelon,
            description: "",
            category: "",
            id: 5,
            amount: 0,
          },
          {
            name: "Danjou Pear",
            price: 80,
            image: DanjouPear,
            description: "",
            category: "",
            id: 6,
            amount: 0,
          },
        ],
      },
      {
        name: "Toilet paper, tissues and wet wipes",
        items: [
          {
            name: "Black Seedless Grapes",
            price: 80,
            image: Grapes,
            description: "",
            category: "",
            id: 1,
            amount: 0,
          },
          {
            name: "Champagne Mango Pack",
            price: 80,
            image: Mango,
            description: "",
            category: "",
            id: 2,
            amount: 0,
          },
          {
            name: "Organic Pink Lady Apples",
            price: 80,
            image: Apples,
            description: "",
            category: "",
            id: 3,
            amount: 0,
          },
          {
            name: "Driscoll's Strawberries",
            price: 80,
            image: Strawberries,
            description: "",
            category: "",
            id: 4,
            amount: 0,
          },
          {
            name: "Seedless Watermelon",
            price: 80,
            image: SeedlessWatermelon,
            description: "",
            category: "",
            id: 5,
            amount: 0,
          },
          {
            name: "Danjou Pear",
            price: 80,
            image: DanjouPear,
            description: "",
            category: "",
            id: 6,
            amount: 0,
          },
        ],
      },
      {
        name: "Laundry and ironing",
        items: [
          {
            name: "Black Seedless Grapes",
            price: 80,
            image: Grapes,
            description: "",
            category: "",
            id: 1,
            amount: 0,
          },
          {
            name: "Champagne Mango Pack",
            price: 80,
            image: Mango,
            description: "",
            category: "",
            id: 2,
            amount: 0,
          },
          {
            name: "Organic Pink Lady Apples",
            price: 80,
            image: Apples,
            description: "",
            category: "",
            id: 3,
            amount: 0,
          },
          {
            name: "Driscoll's Strawberries",
            price: 80,
            image: Strawberries,
            description: "",
            category: "",
            id: 4,
            amount: 0,
          },
          {
            name: "Seedless Watermelon",
            price: 80,
            image: SeedlessWatermelon,
            description: "",
            category: "",
            id: 5,
            amount: 0,
          },
          {
            name: "Danjou Pear",
            price: 80,
            image: DanjouPear,
            description: "",
            category: "",
            id: 6,
            amount: 0,
          },
        ],
      },
      {
        name: "Cleaning accessories",
        items: [
          {
            name: "Black Seedless Grapes",
            price: 80,
            image: Grapes,
            description: "",
            category: "",
            id: 1,
            amount: 0,
          },
          {
            name: "Champagne Mango Pack",
            price: 80,
            image: Mango,
            description: "",
            category: "",
            id: 2,
            amount: 0,
          },
          {
            name: "Organic Pink Lady Apples",
            price: 80,
            image: Apples,
            description: "",
            category: "",
            id: 3,
            amount: 0,
          },
          {
            name: "Driscoll's Strawberries",
            price: 80,
            image: Strawberries,
            description: "",
            category: "",
            id: 4,
            amount: 0,
          },
          {
            name: "Seedless Watermelon",
            price: 80,
            image: SeedlessWatermelon,
            description: "",
            category: "",
            id: 5,
            amount: 0,
          },
          {
            name: "Danjou Pear",
            price: 80,
            image: DanjouPear,
            description: "",
            category: "",
            id: 6,
            amount: 0,
          },
        ],
      },
    ],
  },
  {
    category: "Instant Food",
    id: "010",
    image: InstantFood,
    subCategories: [
      {
        name: "snacks",
        items: [
          {
            name: "Black Seedless Grapes",
            price: 80,
            image: Grapes,
            description: "",
            category: "",
            id: 1,
            amount: 0,
          },
          {
            name: "Champagne Mango Pack",
            price: 80,
            image: Mango,
            description: "",
            category: "",
            id: 2,
            amount: 0,
          },
          {
            name: "Organic Pink Lady Apples",
            price: 80,
            image: Apples,
            description: "",
            category: "",
            id: 3,
            amount: 0,
          },
          {
            name: "Driscoll's Strawberries",
            price: 80,
            image: Strawberries,
            description: "",
            category: "",
            id: 4,
            amount: 0,
          },
          {
            name: "Seedless Watermelon",
            price: 80,
            image: SeedlessWatermelon,
            description: "",
            category: "",
            id: 5,
            amount: 0,
          },
          {
            name: "Danjou Pear",
            price: 80,
            image: DanjouPear,
            description: "",
            category: "",
            id: 6,
            amount: 0,
          },
        ],
      },
      {
        name: "Sweets",
        items: [
          {
            name: "Black Seedless Grapes",
            price: 80,
            image: Grapes,
            description: "",
            category: "",
            id: 1,
            amount: 0,
          },
          {
            name: "Champagne Mango Pack",
            price: 80,
            image: Mango,
            description: "",
            category: "",
            id: 2,
            amount: 0,
          },
          {
            name: "Organic Pink Lady Apples",
            price: 80,
            image: Apples,
            description: "",
            category: "",
            id: 3,
            amount: 0,
          },
          {
            name: "Driscoll's Strawberries",
            price: 80,
            image: Strawberries,
            description: "",
            category: "",
            id: 4,
            amount: 0,
          },
          {
            name: "Seedless Watermelon",
            price: 80,
            image: SeedlessWatermelon,
            description: "",
            category: "",
            id: 5,
            amount: 0,
          },
          {
            name: "Danjou Pear",
            price: 80,
            image: DanjouPear,
            description: "",
            category: "",
            id: 6,
            amount: 0,
          },
        ],
      },
    ],
  },
  {
    category: "Personal Care",
    id: "011",
    image: PersonalCare,
    subCategories: [
      {
        name: "Bathing",
        items: [
          {
            name: "Black Seedless Grapes",
            price: 80,
            image: Grapes,
            description: "",
            category: "",
            id: 1,
            amount: 0,
          },
          {
            name: "Champagne Mango Pack",
            price: 80,
            image: Mango,
            description: "",
            category: "",
            id: 2,
            amount: 0,
          },
          {
            name: "Organic Pink Lady Apples",
            price: 80,
            image: Apples,
            description: "",
            category: "",
            id: 3,
            amount: 0,
          },
          {
            name: "Driscoll's Strawberries",
            price: 80,
            image: Strawberries,
            description: "",
            category: "",
            id: 4,
            amount: 0,
          },
          {
            name: "Seedless Watermelon",
            price: 80,
            image: SeedlessWatermelon,
            description: "",
            category: "",
            id: 5,
            amount: 0,
          },
          {
            name: "Danjou Pear",
            price: 80,
            image: DanjouPear,
            description: "",
            category: "",
            id: 6,
            amount: 0,
          },
        ],
      },
      {
        name: "Oral hygiene",
        items: [
          {
            name: "Black Seedless Grapes",
            price: 80,
            image: Grapes,
            description: "",
            category: "",
            id: 1,
            amount: 0,
          },
          {
            name: "Champagne Mango Pack",
            price: 80,
            image: Mango,
            description: "",
            category: "",
            id: 2,
            amount: 0,
          },
          {
            name: "Organic Pink Lady Apples",
            price: 80,
            image: Apples,
            description: "",
            category: "",
            id: 3,
            amount: 0,
          },
          {
            name: "Driscoll's Strawberries",
            price: 80,
            image: Strawberries,
            description: "",
            category: "",
            id: 4,
            amount: 0,
          },
          {
            name: "Seedless Watermelon",
            price: 80,
            image: SeedlessWatermelon,
            description: "",
            category: "",
            id: 5,
            amount: 0,
          },
          {
            name: "Danjou Pear",
            price: 80,
            image: DanjouPear,
            description: "",
            category: "",
            id: 6,
            amount: 0,
          },
        ],
      },
      {
        name: "Hygiene products",
        items: [
          {
            name: "Black Seedless Grapes",
            price: 80,
            image: Grapes,
            description: "",
            category: "",
            id: 1,
            amount: 0,
          },
          {
            name: "Champagne Mango Pack",
            price: 80,
            image: Mango,
            description: "",
            category: "",
            id: 2,
            amount: 0,
          },
          {
            name: "Organic Pink Lady Apples",
            price: 80,
            image: Apples,
            description: "",
            category: "",
            id: 3,
            amount: 0,
          },
          {
            name: "Driscoll's Strawberries",
            price: 80,
            image: Strawberries,
            description: "",
            category: "",
            id: 4,
            amount: 0,
          },
          {
            name: "Seedless Watermelon",
            price: 80,
            image: SeedlessWatermelon,
            description: "",
            category: "",
            id: 5,
            amount: 0,
          },
          {
            name: "Danjou Pear",
            price: 80,
            image: DanjouPear,
            description: "",
            category: "",
            id: 6,
            amount: 0,
          },
        ],
      },
      {
        name: "Perfumery",
        items: [
          {
            name: "Black Seedless Grapes",
            price: 80,
            image: Grapes,
            description: "",
            category: "",
            id: 1,
            amount: 0,
          },
          {
            name: "Champagne Mango Pack",
            price: 80,
            image: Mango,
            description: "",
            category: "",
            id: 2,
            amount: 0,
          },
          {
            name: "Organic Pink Lady Apples",
            price: 80,
            image: Apples,
            description: "",
            category: "",
            id: 3,
            amount: 0,
          },
          {
            name: "Driscoll's Strawberries",
            price: 80,
            image: Strawberries,
            description: "",
            category: "",
            id: 4,
            amount: 0,
          },
          {
            name: "Seedless Watermelon",
            price: 80,
            image: SeedlessWatermelon,
            description: "",
            category: "",
            id: 5,
            amount: 0,
          },
          {
            name: "Danjou Pear",
            price: 80,
            image: DanjouPear,
            description: "",
            category: "",
            id: 6,
            amount: 0,
          },
        ],
      },
    ],
  },
  {
    category: "Pet Care",
    id: "012",
    image: PetCare,
    subCategories: [
      {
        name: "Pet Care",
        items: [
          {
            name: "Black Seedless Grapes",
            price: 80,
            image: Grapes,
            description: "",
            category: "",
            id: 1,
            amount: 0,
          },
          {
            name: "Champagne Mango Pack",
            price: 80,
            image: Mango,
            description: "",
            category: "",
            id: 2,
            amount: 0,
          },
          {
            name: "Organic Pink Lady Apples",
            price: 80,
            image: Apples,
            description: "",
            category: "",
            id: 3,
            amount: 0,
          },
          {
            name: "Driscoll's Strawberries",
            price: 80,
            image: Strawberries,
            description: "",
            category: "",
            id: 4,
            amount: 0,
          },
          {
            name: "Seedless Watermelon",
            price: 80,
            image: SeedlessWatermelon,
            description: "",
            category: "",
            id: 5,
            amount: 0,
          },
          {
            name: "Danjou Pear",
            price: 80,
            image: DanjouPear,
            description: "",
            category: "",
            id: 6,
            amount: 0,
          },
        ],
      },
    ],
  },
];

export const getCategories = async () => {
  try {
    const data = await fetch("/api/products/categories");
    if (data) {
      const categories = await data.json();
      console.log(`this is categories: ${categories[0].image}`);
      return categories;
    }
  } catch (error) {
    console.log(error.message);
  }
};

export const getItemsByCategory = async (categoryName) => {
  const items = AllItems.find((obj) => obj.category === categoryName);
  return items;
};

export const getItemsBySubCategory = async (categoryName, subName) => {
  const items = await getItemsByCategory(categoryName);
  const subItems = items.subCategories.find((obj) => obj.name === subName);
  return { category: items.category, subCategories: [{ ...subItems }] };
};

export const mainScreenItems = () => {
  //allItems = categories Array
  const allItemsLength = AllItems.length;
  let items = [];

  for (let i = 0; i < 3; i++) {
    let chosenItems = [];
    const randomCategory = getRandom(allItemsLength);
    const randomSub = getRandom(AllItems[randomCategory].subCategories.length);

    // push only 6 items
    for (let i = 0; i < 6; i++) {
      chosenItems.push(
        AllItems[randomCategory].subCategories[randomSub].items[i]
      );
    }

    items.push({
      category: AllItems[randomCategory].category,
      subCategory: AllItems[randomCategory].subCategories[randomSub].name,
      items: chosenItems,
    });
  }
  return items;
};
